{% set name = "dotmap" %}
{% set version = "1.3.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5821a7933f075fb47563417c0e92e0b7c031158b4c9a6a7e56163479b658b368

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  imports:
    - dotmap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drgrib/dotmap
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Ordered, dynamically-expandable dot-access dictionary
  dev_url: https://github.com/drgrib/dotmap
  doc_url: https://github.com/drgrib/dotmap

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
